import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// 🔴 แก้ไขบรรทัดนี้ ให้ถอยออกไปหาโฟลเดอร์ context
import { AppProvider } from "../context/AppContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body>{children}</body>
    </html>
  );
}
